### ISSUE TITLE
What is the DUMP_FILE in load_quandl_sf1.py?

### ISSUE THREAD

**Issue by zukangy** [pbharrin/alpha-compiler#7]
Hey, @pbharrin, I was implementing your way of loading the fundamentals data, and after a series of modifications, as I tried to run load_quandl_sf1.py, it says no file named /Users/xxx/.../SHARADAR_SF1_2daa4baaad2a300c166b5c0f7e546bd1.csv'.

In order to fix it, I manually created the csv file and put it into the right folder, but I got another error message saying that 

pandas.errors.EmptyDataError: No columns to parse from file 

I am wondering what the dump file is in the load_quandl_sf1.py? 

best,

**Comment by pbharrin** [comment]
The dump file is a bulk download from Sharadar's SF1 dataset from Quandl.  
Are you using fundamentals from Sharadar SF1 or some other fundamentals?

**Comment by zukangy** [comment]
ok thanks!
