### ISSUE TITLE
require argument country_code 

### ISSUE THREAD

**Issue by zukangy** [pbharrin/alpha-compiler#8]
Hey @pbharrin, I did all the necessary modifications, and as I ran load_quandl_sf1.py, I got the error below.

-------
Loading Extensions

Traceback (most recent call last):
  File "/Users/zukangy/Desktop/Eonum/alpha-compiler/alphacompiler/data/load_quandl_sf1.py", line 218, in <module>
    num_tickers = num_tkrs_in_bundle(BUNDLE_NAME)
  File "/Users/zukangy/Desktop/Eonum/alpha-compiler/alphacompiler/data/load_quandl_sf1.py", line 181, in num_tkrs_in_bundle
    return len(get_ticker_sid_dict_from_bundle(bundle_name))
  File "/Users/zukangy/Desktop/Eonum/alpha-compiler/alphacompiler/util/zipline_data_tools.py", line 95, in get_ticker_sid_dict_from_bundle
    all_equities = get_tickers_from_bundle(bundle_name)
  File "/Users/zukangy/Desktop/Eonum/alpha-compiler/alphacompiler/util/zipline_data_tools.py", line 69, in get_tickers_from_bundle
    lifetimes = bundle_data.asset_finder._compute_asset_lifetimes()
TypeError: _compute_asset_lifetimes() missing 1 required positional argument: 'country_codes'

Process finished with exit code 1
-------

do you have any recommendations or what the country_code should be?

**Comment by pbharrin** [comment]
Thanks for pointing that out.  [Looks like that method changed](https://github.com/quantopian/zipline/blob/695117cca791f0d3029994b4a905b25816ae406f/zipline/assets/assets.py#L1419).  I updated Zipline within in the last two months and didn't get that error.   The commit is from Novemer 2019, perhaps it was not released until recently.  

Try to add None as the only argument to [line 69](https://github.com/pbharrin/alpha-compiler/blob/master/alphacompiler/util/zipline_data_tools.py#L69) of  get_tickers_from_bundle().
Like this: 
`lifetimes = bundle_data.asset_finder._compute_asset_lifetimes(None)`

**Comment by zukangy** [comment]
Changing the arg to None does make the program run, but it gives me an output where "no tickers are found", same thing happened if I change the arg to 'us' or 'US'. 

But your program works for me switching back to python 2.7 with the corresponding zipline version. Thanks for your effort, hope alpha-complier will be more robustly functioning on diff versions of zipline soon!

**Comment by pbharrin** [comment]
The country code should be 'US'.  I would like to duplicate the issue, what version of Zipline were you running when this happened?  How did you install it?  Did you build it from the source?

**Comment by zukangy** [comment]
The Python version is 3.6 and the zipline version is zipline-live2. 

The error after specifying the country_code to be 'US', looks like this:

Loading Extensions

number of tickers:  0
   **   clearing the raw/ folder   **
processing:  A
no sid found for: A
processing:  AA
no sid found for: AA
processing:  AAAP
no sid found for: AAAP
processing:  AACG
no sid found for: AACG
processing:  AACH
no sid found for: AACH
processing:  AAL
no sid found for: AAL
processing:  AAMC
no sid found for: AAMC
processing:  AAME
no sid found for: AAME
processing:  AAN
no sid found for: AAN
processing:  AAOI
:
:
:
no sid found for: ZYXI
this worked boss

Process finished with exit code 0

**Comment by FrankPSch** [comment]
Hey @pbharrin, same here on zipline-live2 with Py3.6, all pip-installed.

Initially, 'python load_quandl_sf1.py' says 'number of tickers: 0'.

The 'extension.py' includes:
`
def sep():
    register(
        "sep",
         from_sep_dump(
            "C:/Users/Frank/.zipline/alpha_dump/SHARADAR_SEP_b449cf91394bfd946c3c32e72ee7efb6.csv"
         ),
    )
`

However, 'zipline ingest -b sep' returns:
`Abnormal returns for: AAIIQ
date
2013-01-16    4.00
2015-04-30    6.25
Name: close, dtype: float64
Abnormal returns for: ABCP
date
2011-09-01    3.096774
Name: close, dtype: float64
Abnormal returns for: ABEOW
date
2019-09-03    3.324324
Name: close, dtype: float64`

and then finally confirms
`a total of 10949 securities were loaded into this bundle`

If I change 'zipline_data_tools.py' to
`lifetimes = bundle_data.asset_finder._compute_asset_lifetimes('US')
print('len(lifetimes.sid):', len(lifetimes.sid))`

it returns
`len(lifetimes.sid): 0
number of tickers:  0
len(lifetimes.sid): 0`

-----------------
To further identify where this could come from, I made a smaller SEP file and added some prints. Here are the results from 'zipline ingest -b sep':
`SEP_QANDL.PY: running "from_sep_dump"`
`SEP_QANDL.PY: starting ingesting data from: C:/Users/Frank/.zipline/alpha_dump/SHARADAR_SEP_short.csv`
`SEP_QANDL.PY: preparing A`
`SEP_QANDL.PY: preparing AA`
`SEP_QANDL.PY: preparing AACG`
`SEP_QANDL.PY: preparing AAGIY`
`SEP_QANDL.PY: preparing AAL`
`SEP_QANDL.PY: preparing AAMC`
`SEP_QANDL.PY: preparing AAME`
`SEP_QANDL.PY: preparing AAN`
`SEP_QANDL.PY: preparing AAOI`
`SEP_QANDL.PY: preparing AAON`
`SEP_QANDL.PY: preparing AAP`
`SEP_QANDL.PY: preparing AAPL`
`SEP_QANDL.PY: writing data for 12 securities`
`SEP_QANDL.PY: a total of 12 securities were loaded into this bundle`
`SEP_QANDL.PY: total 0 dividends found`
`SEP_QANDL.PY: a total of 0 dividends were loaded into this bundle`

and then the result from 'load_quandl_sf1.py':
`Loading Extensions`
`SEP_QANDL.PY: running "from_sep_dump"`

`ZIPLINE_DATA_Tools: running "get_tickers_from_bundle"`
`bundle_data: BundleData(asset_finder=<zipline.assets.assets.AssetFinder object at 0x000001C20882B0B8>, equity_minute_bar_reader=<zipline.data.minute_bars.BcolzMinuteBarReader object at 0x000001C23BB23748>, equity_daily_bar_reader=<zipline.data.us_equity_pricing.BcolzDailyBarReader object at 0x000001C23BB23710>, adjustment_reader=<zipline.data.us_equity_pricing.SQLiteAdjustmentReader object at 0x000001C23BB23DA0>)`
`len(lifetimes.sid): 0`

`number of tickers:  0`

`ZIPLINE_DATA_Tools: running "get_tickers_from_bundle"`
`bundle_data: BundleData(asset_finder=<zipline.assets.assets.AssetFinder object at 0x000001C20882B0B8>, equity_minute_bar_reader=<zipline.data.minute_bars.BcolzMinuteBarReader object at 0x000001C23BB23748>, equity_daily_bar_reader=<zipline.data.us_equity_pricing.BcolzDailyBarReader object at 0x000001C23BB23710>, adjustment_reader=<zipline.data.us_equity_pricing.SQLiteAdjustmentReader object at 0x000001C23BB23DA0>)`
`len(lifetimes.sid): 0`

`   **   clearing the raw/ folder   **`
`processing:  Av
`no sid found for: A`

and so on. So the error seems to be in the following line
`lifetimes = bundle_data.asset_finder._compute_asset_lifetimes('US')`

**Comment by life-elixir** [comment]
For now, please focus on the zipline based on the python 3.5 version posted in anaconda and it works fine there. I think @pbharrin will release a version that works well with zipline-live2 as well but all you have to do is to replace the zipline folder in the zipline-live2 folder with the anaconda version here:
conda install -c quantopian zipline

**Comment by carstenf** [comment]
To be able to get closer to a solution me must fix "No bundle registered with the name 'sep' #9"
This is now working and we get the additional information written into the SQLite, like the country code.

The main issue seems to be in zipline_data_tools.py
Then there are to small changes in the header, at least I got some errors due to this:

`#from zipline.pipeline import SimplePipelineEngine, USEquityPricingLoader
from zipline.pipeline.loaders import USEquityPricingLoader # zipline 1.4
from zipline.pipeline.engine import SimplePipelineEngine # zipline 1.4
`

I added the correct country code as an argument to 
bundle_data.asset_finder._compute_asset_lifetimes('US')

in the following function, around line 85

`
def get_tickers_from_bundle(bundle_name):

    bundle_data = load(bundle_name, os.environ, None)
    # get a list of all sids
    #lifetimes = bundle_data.asset_finder._compute_asset_lifetimes()
    lifetimes = bundle_data.asset_finder._compute_asset_lifetimes(str('US'))
    all_sids = lifetimes.sid
    print(all_sids)
    # retreive all assets in the bundle
    all_assets = bundle_data.asset_finder.retrieve_all(all_sids)
    # return only tickers
    return map(lambda x: (x.symbol, x.sid), all_assets)`

but did not solved the issue.
I did  print(all_sids)  but no sids were returned. Maybe the country code has to be differently specified? 
according to the zipline documentation it should be a string.
I checked as well in the SQLite and US is in the database. (I used DB Browser for SQLite)

Maybe someone as a better idea?

**Comment by carstenf** [comment]
I took a look at assets.py in zipline, where you find the function _compute_asset_lifetimes line 1419

'US' arrived there as as sting and passes the first if

unfortunately it did not pass the second argument from the next when

If you comment   (self.exchanges.c.country_code.in_(country_codes)) this part, everything is working.
like below. 
BUT this is not the solution, just closer to the issue.

The function def _compute_asset_lifetimes in 3.5 looks totally and completely different


`def _compute_asset_lifetimes(self, country_codes):

        sids = starts = ends = []
        equities_cols = self.equities.c
        if country_codes:
            results = sa.select((
                equities_cols.sid,
                equities_cols.start_date,
                equities_cols.end_date,
            )).where(
                (self.exchanges.c.exchange == equities_cols.exchange) 
          #& (self.exchanges.c.country_code.in_(country_codes))
            ).execute().fetchall()
            if results:
                sids, starts, ends = zip(*results)`

**Comment by pbharrin** [comment]
Here are the changes for 1.4.  If anyone can spot what change may have broken the code that would be helpful.  
https://www.zipline.io/releases.html#release-1-4-0

**Comment by carstenf** [comment]
International Pipelines

in assets.py, they changed 

def _compute_asset_lifetimes

Completely, totally new/different code

Take look. 

Maybe we need more than to just send the string US, I guess it’s not precisely what this parts needs to give a TRue

(self.exchanges.c.country_code.in_(country_codes))


This has to be True with the right country code.

Than your issue is solved!


Am 11.01.2021 um 17:20 schrieb Peter Harrington <notifications@github.com>:

﻿
Here are the changes for 1.4. If anyone can spot what change may have broken the code that would be helpful.
https://www.zipline.io/releases.html#release-1-4-0

**Comment by carstenf** [comment]
the changes are due to International Pipelines

we need to use a frozenset for the country codes, as an argument in both functions in zipline_data_tools.py below, than it should work

frozenset([str("US")]) 

`

def get_tickers_from_bundle(bundle_name):
    """Gets a list of tickers from a given bundle"""
    bundle_data = load(bundle_name, os.environ, None)

    # get a list of all sids
    #lifetimes = bundle_data.asset_finder._compute_asset_lifetimes()
    lifetimes = bundle_data.asset_finder._compute_asset_lifetimes(frozenset([str("US")]))
    all_sids = lifetimes.sid
    print(all_sids)

    # retreive all assets in the bundle
    all_assets = bundle_data.asset_finder.retrieve_all(all_sids)

    # return only tickers
    return map(lambda x: (x.symbol, x.sid), all_assets)


def get_all_assets_for_bundle(bundle_name):
    """For a given bundle get a list of all assets"""
    bundle_data = load(bundle_name, os.environ, None)

    # get a list of all sids
    lifetimes = bundle_data.asset_finder._compute_asset_lifetimes(frozenset([str("US")]))
    all_sids = lifetimes.sid

    print('all_sids: ', all_sids)

    # retreive all assets in the bundle
    return bundle_data.asset_finder.retrieve_all(sids=all_sids)

`

**Comment by pbharrin** [comment]
This is now fixed, closing this issue.  Thank you for the help @carstenf
