### ISSUE TITLE
No bundle registered with the name 'sep'

### ISSUE THREAD

**Issue by octaviodegodoy** [pbharrin/alpha-compiler#9]
Hi, I was following the instructions for installing on window, but after running the script load_quandl_sf1.py I got the error "No bundle registered with the name 'sep' "

Updated with zipline ingest, set my quandl key properly but could not solve it. 
Thank you for any help.

**Comment by FrankPSch** [comment]
Hi Luiz,

I am currently also working on a proper installation and have been able to solve your questions yesterday ;).

Some questions to you, my current trial is in brackets:
- Which versions do you use for python (py36 from python.org), zipline (zipline-live2), broker connectivity (IBpy2 from zipline-live2)?

Some hints from me:
- In the /data/loaders/ directory, you can find the file 'sep_quandl.py' which you need to run before the 'load_quandl_sf1.py'.

- Inside this file, you will also find an explanation on how to register 'sep' in '~/.zipline/extension.py' which needs to be done before.

- As I have not yet managed to run 'NASDAQ_sector_code_loader.py' or 'SHARADAR_sector_code_loader.py', I have commented out the line 'from alphacompiler.data.NASDAQ import NASDAQSectorCodes' in the examples.

Have fun,
Frank

**Comment by FrankPSch** [comment]
Also:

-  In file 'sparse_data.py', the class SparseDataFactor requires that the path 'self.data_path' is correctly set.

**Comment by carstenf** [comment]
Zipline 1.4 requires more information for exchange 

Following changes in sep_quandl.py are necessary for zipline 1.4

Metadate sep need to be changed to "NYSE", line 5

`            metadata_list.append((df_tkr.index[0],
                                  df_tkr.index[-1],
                                  df_tkr.index[-1] + pd.Timedelta(days=1),
                                  row0["ticker"],
                                  "NYSE",    # zipline 1.4 change to NYSE
                                  row0["ticker"]  # TODO: can we delete this?
                                  )
                                 )
`

Than in line 110 change the following:

`        exchange = {'exchange': 'NYSE', 'canonical_name': 'NYSE', 'country_code': 'US'}  # changes for zipline 1.4                                    
        exchange_df = pd.DataFrame(exchange,index = [0])  # changes for zipline 1.4 

        # write metadata
        #asset_db_writer.write(equities=pd.DataFrame(metadata_list,
        #                                            columns=METADATA_HEADERS))
        asset_db_writer.write(equities=pd.DataFrame(metadata_list,
                                                    columns=METADATA_HEADERS),
                                                    exchanges=exchange_df  # changes for zipline 1.4 
                                                    )`


  with this changes you should be able to read the registered bundle.

This is the base to fix "require argument country_code"

**Comment by pbharrin** [comment]
This is now fixed, make sure your loader sets the country code [like this](https://github.com/pbharrin/alpha-compiler/blob/master/alphacompiler/data/loaders/sep_quandl.py#L13).
